### ISSUE TITLE
Add identifiers field to CITATION.cff after first release

### ISSUE THREAD

**Issue by RMeli** [eth-cscs/DLA-Future-Fortran#4]
We need the first release to generate a DOI on [Zenodo](https://zenodo.org/).

```yaml
identifiers:
  - description:
    type: doi
    value:
```
